In [1]:
import numpy as np

In [2]:
array_1= np.array([1,3,4,5])

In [3]:
array_1

array([1, 3, 4, 5])

In [4]:
array_1*[3]

array([ 3,  9, 12, 15])

In [5]:
array_1 + [3]

array([4, 6, 7, 8])

In [6]:
rooms_length = np. array([10,12,13,14])

In [7]:
rooms_width = np.array([2,3,5,6])

In [8]:
room_size_each= rooms_length*rooms_width
print(room_size_each)

[20 36 65 84]


In [9]:
#TEMPERATURE CONVERSION ASSIGNMENT


In [10]:
NYC_monthly_temp_F=[20,24,60,60,70,55,60,100,80,50,60,59]
print(NYC_monthly_temp_F)

[20, 24, 60, 60, 70, 55, 60, 100, 80, 50, 60, 59]


In [11]:
#to convert temp to Celcius


In [12]:
NYC_monthly_temp_F=np.array([20,24,60,60,70,55,60,100,80,50,60,59])

In [13]:
NYC_monthly_temp_C =np.array(NYC_monthly_temp_F -32) *(5/9)
print(NYC_monthly_temp_C)

[-6.66666667 -4.44444444 15.55555556 15.55555556 21.11111111 12.77777778
 15.55555556 37.77777778 26.66666667 10.         15.55555556 15.        ]


In [14]:
#Generating Some Mock Data

In [15]:
py_list=(0,1,2,3,4,5)

In [16]:
py_range= list(range(0,5,1))

In [17]:
print(py_range)

[0, 1, 2, 3, 4]


In [19]:
array_for_list=np.array(py_list)
array_for_list

array([0, 1, 2, 3, 4, 5])

In [20]:
array_for_range=np.array(py_list)
array_for_range

array([0, 1, 2, 3, 4, 5])